# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        types:
          - python
      - id: end-of-file-fixer
        types:
          - python
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: 'migrations'
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys, --expand-star-imports]
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        exclude: 'migrations'
        args:
          - --profile=black
          - --line-length=120
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        exclude: 'migrations'
        args:
          - --py39-plus
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        language_version: py3.9
        exclude: ".*/migrations/.*"
        args:
          - --line-length=120
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: 'migrations'
        additional_dependencies:
          - flake8-bugbear
          - flake8-django
          - flake8-comprehensions
          - flake8-simplify
        args:
          - --max-line-length=120
#          - --select=E, F, W, C90  flake8 default
          - --extend-ignore=E203, W503, F405, SIM104, SIM106, SIM119, F821, DJ03

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.32.0'
    hooks:
      - id: eslint
        args:
          - --fix
        additional_dependencies: [ 'eslint@7.32.0', 'eslint-config-prettier', 'eslint-plugin-prettier' ]
        files: 'django_filter_groups/'
        exclude: 'min.js$'
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.0
    hooks:
      - id: curlylint
        files: 'templates/'
  - repo: https://github.com/rtts/djhtml
    rev: 'v1.4.9'
    hooks:
      - id: djhtml
        args:
        - --tabwidth=2
        files: 'templates/'
