# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        types:
          - python
      - id: end-of-file-fixer
        types:
          - python
      - id: mixed-line-ending
        args: [--fix=crlf]
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        exclude: 'migrations'
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys, --expand-star-imports]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: 'migrations'
        args:
          - --profile=black
          - --line-length=120
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        exclude: 'migrations'
        args:
          - --py39-plus
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: py3.9
        exclude: ".*/migrations/.*"
        args:
          - --line-length=120
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: 'migrations'
        additional_dependencies:
          - flake8-bugbear
          - flake8-django
          - flake8-comprehensions
          - flake8-simplify
        args:
          - --max-line-length=120
#          - --select=E, F, W, C90  flake8 default
          - --extend-ignore=E203, W503, F405, SIM104, SIM106, SIM119, F821, DJ03

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: '0.0.2' # Use the sha or tag you want to point at like 0.0.1
    hooks:
      - id: stylelint
        args:
          - --fix
        additional_dependencies: [ 'stylelint@13.2.1', 'stylelint-config-twbs-bootstrap@2.2.3' ]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.26.0'
    hooks:
      - id: eslint
        args:
          - --fix
        additional_dependencies: [ 'eslint@7.32.0', 'eslint-config-prettier', 'eslint-plugin-prettier' ]
        files: 'django_filters_groups/'
        exclude: 'min.js$'
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        files: 'templates/'
  - repo: https://github.com/rtts/djhtml
    rev: 'v1.5.2'
    hooks:
      - id: djhtml
        args:
        - --tabwidth=2
        files: 'templates/'
